name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Definir JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Gerar .jar
        env:
          SERVICE_ENDPOINT: ${{secrets.SERVICE_ENDPOINT}}
          SIGNING_REGION: ${{secrets.SIGNING_REGION}}
          ACCESS_KEY: ${{secrets.ACCESS_KEY}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
        run: |
          mvn -B clean package \
          -Dspring.profiles.active=test \
          -Ddynamo.serviceEndpoint=$SERVICE_ENDPOINT \
          -Ddynamo.signingRegion=$SIGNING_REGION \
          -Ddynamo.accessKey=$ACCESS_KEY \
          -Ddynamo.secretKey=$SECRET_KEY \
          --file pom.xml
      - name: docker build
        run: docker build -t gustosilva/dynamodb-api .
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
        run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN
      - name: docker tag
        run: docker tag $(docker images --filter=reference='gustosilva/dynamodb-api' --format "{{.ID}}") gustosilva/dynamodb-api
      - name: docker push
        run: docker push gustosilva/dynamodb-api
      - name: docker logout
        run: docker logout