name: Docker Image CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Definir JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Gerar .jar
        run: mvn -B clean package -DskipTests --file pom.xml
      - name: docker build
        run: docker build -t gustosilva/dynamodb-api .


#      - name: docker login
#        env:
#          DOCKER_USER: ${{secrets.DOCKER_USER}}
#          DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
#        run: docker login -u $DOCKER_USER -p $DOCKER_TOKEN
#      - name: docker build
#        run: docker build --file Dockerfile --tag gustosilva/dynamodb-api:$(date +%s) .
#      - name: docker push
#        run: docker push gustosilva/dynamodb-api